#!/bin/bash

if [[ $# -lt 2 ]]; then
    echo "Usage: edit <editor> <file/path>"
    exit 1
fi

editor="$1"
shift
file="$*"

if [[ ! -f "$file" ]]; then
    echo "Error: File '$file' Khong Ton Tai."
    exit 1
fi

if [[ "$editor" == "vsc" ]]; then
 code "$file"
elif [[ "$editor" == "gte" ]]; then
 gnome-text-editor "$file"
elif [[ "$editor" == "nn" ]]; then
 nano "$file"
elif [[ "$editor" == "vm" ]]; then
 vim "$file"
else
 $editor "$file"
fi
