#!/bin/bash
echo "C++ Compiler - Manual" 
echo "Vui Long Nhap File Can Bien Dich (Duong dan hoac ./file.cpp)"
read -p ">> " file
if [[ "$file" == "exit" || "$file" == "q" || "$file" == "exit m-run" ]]; then 
echo "Exit..."
exit 0
fi
if [[ ! -f "$file" ]]; then 
echo "Error: File '$file' Khong Ton Tai" 
exit 1 
fi 

compilerDone="${file%.*}"
g++ "$file" -o "$compilerDone" 

if [[ $? -eq 0 ]]; then 
./"$compilerDone" 
else 
echo "Bien dich that bai!" 
exit 1
fi
